### ISSUE TITLE
Plexon is not defined in Windows

### ISSUE THREAD

**Issue by hndr91** [pearsonlab/pygonogo#6]
I found this error in Windows based
```
pyo version 0.8.0 (uses single precision)
{'Task Name': 'gonogo', 'Subject': 'test'}
16.1464 	WARNING 	Requested an unavailable screen number - using first available.
16.1471 	WARNING 	User requested fullscreen with size [800 600], but screen is actually [1366, 768]. Using actual size
Traceback (most recent call last):
  File "E:\pygonogo\gonogo.py", line 8, in <module>
    mytask = task.Task()
  File "E:\pygonogo\task.py", line 26, in __init__
    self.setup()
  File "E:\pygonogo\task.py", line 44, in setup
    if Plexon:
NameError: global name 'Plexon' is not defined
portaudio error in Pa_AbortStream: Unanticipated host error
```

**Comment by jmxpearson** [comment]
Sorry, not running Windows anymore. Can you try changing line 17 to 
```python
PlexClient = None
```
and line 44 to 
```python
if PlexClient:
```
and let me know if that works?

**Comment by hndr91** [comment]
I'll try it sir,
Sorry for bothering you, I have one question. I have tried to modify your code to generate custom log in PyschoPy2. I'm sure that my code should be fine, but, PyschoPy2 didn't generate my log. What is going on actually ? Thanks

**Comment by jmxpearson** [comment]
Sorry, but while I can fix bugs in our code, I can't really help you debug your own (especially without source).

**Comment by hndr91** [comment]
Sir, I got this after fixing PlexClient
```
Traceback (most recent call last):
  File "E:\pygonogo\gonogo.py", line 8, in <module>
    mytask = task.Task()
  File "E:\pygonogo\task.py", line 26, in __init__
    self.setup()
  File "E:\pygonogo\task.py", line 49, in setup
    self.logger = initializers.setup_logging(self.data, self.plexon)
  File "E:\pygonogo\initializers.py", line 34, in setup_logging
    plexon.InitClient()
  File "E:\pygonogo\Plexon\PlexClient.py", line 64, in InitClient
    raise RuntimeError("Failed to initiate Plexon client.")
RuntimeError: Failed to initiate Plexon client.
portaudio error in Pa_AbortStream: Unanticipated host error
```

**Comment by hndr91** [comment]
I'm sorry Sir, I fixed it by set PlexClient to None, event if OS under 'nt'. May I ask you a question, What does Plexon library actually do ?

**Comment by jmxpearson** [comment]
http://www.plexon.com/

We used Plexon as a data acquisition system for brain recording. I will eventually fix this, but I need to get hold of a Windows machine. Glad you got yours working.
